application: toosmartbrain
version: 1
runtime: php55
api_version: 1
threadsafe: false
module: dev

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: .*
  script: index.html